version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: example
    ports:
    - "5672:5672"
    - "8080:15672"